# -*- coding: utf-8 -*-
"""task1_numpy_arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DWeYLXsssisbUp4Hc9VHmWYGCPYe3KH
"""

import numpy as np

#Creating a NumPy array containing at least 10 numbers
lst=[28,89,45,54,67,78,942,546,9876,6336]
arr=np.array(lst)

#Displaying the array
print("NumPy Array:")
print(arr)

#displays the array's shape, size, and data type.
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)

#Creates a one-dimensional and two-dimensional array
arr1=np.array([1,3,5,7,9,11])
arr2=np.array([[1,2,3],
             [4,5,6]])
print("One-Dimensional Array:")
print(arr1)
print("Shape of 1d array: ",arr1.shape)
print("Two-Dimensional Array:")
print(arr2)
print("Shape of 2d array:",arr2.shape)

