# -*- coding: utf-8 -*-
"""task3_numpy_operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSITSLc3HmYvdilONlhtHncdG1RRoz9W
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('Simple 100 Student Marks.csv')
df.head()

marks=df['maths_marks'].to_numpy()
print(marks)

#Mathematical Operations
print("Addition :",marks+5)
print("Subtraction: ",marks-5)
print("Multiplication:",marks*5)
print("Division: ",marks/5)

#Statistical Operations
print("Mean :",np.mean(marks))
print("Median :",np.median(marks))
print("Minimum :",np.min(marks))
print("Maximum :",np.max(marks))
print("Standard Deviation:", np.std(marks))
print("Sum: ",np.sum(marks))