# -*- coding: utf-8 -*-
"""Task_8_9_Pandas_Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PupJG48EqCOBVzm4DQU3TJFaIjoC6XkL
"""

import pandas as pd

from google.colab import files
uploaded=files.upload()

df1=pd.read_csv('customer_data.csv')
df2=pd.read_csv('sales_data (1).csv')

df1.head()

df2.head()

merged_csv=pd.merge(df1,df2,on="Customer_ID")
merged_csv.head()

#Concat
sales_df1=df2.iloc[:50]
sales_df2=df2.iloc[50:]
sales=pd.concat([sales_df1,sales_df2])

sales.head()

#Usage of groupby and aggregation functions
category_analysis=sales.groupby('Category')['Total_Sales'].agg(["sum","mean","count","min","max"])
print(category_analysis)

merged_csv

pivot_table=pd.pivot_table(merged_csv,
                           columns="Product",
                           index="City",
                           values="Total_Sales",
                           aggfunc="sum")
pivot_table

merged_csv.to_csv("final_processed_data.csv",index=False)

from google.colab import files
files.download('final_processed_data.csv')