# -*- coding: utf-8 -*-
"""task7_missing_values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iD05P2XQNtxGkldYPQj5at9MYxtaHvsA
"""

import pandas as pd

from google.colab import files
uploaded=files.upload()

#Before handling missing values
df=pd.read_csv('retail_store_sales.csv')
df.head()

df.info()

df.isnull().sum()

df['Item']=df['Item'].fillna(df.groupby('Category')['Item'].transform(lambda x:x.fillna(x.mode()[0])))

df['Price Per Unit']=df['Price Per Unit'].fillna(df['Price Per Unit'].median())

df['Quantity']=df['Quantity'].fillna(df['Quantity'].median())

df['Total Spent']=df['Total Spent'].fillna(df['Total Spent'].median())

df['Discount Applied']=df['Discount Applied'].fillna(df['Discount Applied'].mode())

df.isnull().sum()

df.info()

#After handling missing values
df.head()