# -*- coding: utf-8 -*-
"""task6_filtering_sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jN0IApUy3G5T0rGHkGyLFiVHp1PdBicD
"""

import pandas as pd

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('Superstore.csv',encoding='latin1')
df.head()

df.info()

#selecting specific column
selected_columns=df[['Segment','Country','City','Postal Code','Region']]
selected_columns.head(15)

#selecting specific row
specific_rows=df.iloc[0:5]
specific_rows

df.iloc[[0, 2, 4]]

#filtering records using one condition
profitable_sales=df[df['Sales']>200]
profitable_sales.head()

high_sales_profit=df[(df['Sales']>500) & (df['Profit']>200)]
high_sales_profit.head()

#sort data by sales in ascending order
df.sort_values("Sales")

#Sort data by sales in descending order
df.sort_values("Sales",ascending=False)