# -*- coding: utf-8 -*-
"""task4_pandas_dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1B3vkN4Hrz4Nmk0_FYL4dSakS6RZWnw
"""

import pandas as pd

# Pandas Series.
series=pd.Series([20,40,60,80,100,120,140,160,180,200])
print(series)

# Pandas DataFrame
df=pd.DataFrame({"std_names ": ["Meera","Madhu","Ram","Sheela","Swapna","Rohit"],
                "rollno":[101,102,104,111,150,132],
                "Marks":[95,90,78,80,75,30]})
print(df)

# column names
print(df.columns)

#index
print(df.index)

#accessing using index
df.loc[2]

df["Grades"]=['A','A','B','B','B','E']
print("updated dataframe : ")
print(df)