# -*- coding: utf-8 -*-
"""task5_reading_inspecting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ja6Zs5D3dsGn7Y7UrXcCw0yRDxEeyd2K
"""

import pandas as pd

from google.colab import files
uploaded=files.upload()

#Reading csv file
df=pd.read_csv('Superstore.csv',encoding='latin1')
#first 5 rows
df.head()

#last 5 rows
df.tail()

#Number of rows and columns
df.shape

#Column Names
df.columns

#Data types
df.dtypes

df.info()

df.describe(include='all')