# -*- coding: utf-8 -*-
"""task2_indexing_slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2j_sco-5vd89hbVdNk194gIgMfZ52gf
"""

import numpy as np

# Create a 1D NumPy array
lst=[10,20,30,40,50,60,70,80,90,100]
arr1=np.array(lst)

#Indexing
print(arr1[0])
print(arr1[-1])
print(arr1[5])
print(arr1[-3])

#Slicing
print(arr1[3:9])
print(arr1[::-1])
print(arr1[1:10:2])
print(arr1[:-2])
print(arr1[:])

#2d array
arr2=np.array([
    [1,2,3],
    [6,7,8],
    [9,10,11],
    [2,4,6]
])
print(arr2)

#Row slicing
print(arr2[2:])
print(arr2[1:2])
print(arr2[-2:])

#column slicing
print(arr2[1:3,0:2])

##Reshape the 1D array
reshaped = arr1.reshape(5,2)

print("Original Array: \n",arr1)
print("Reshaped Array: \n",reshaped)

reshaped_2d=arr2.reshape(3,4)
print("Original Array: \n",arr2)
print("Reshaped Array: \n",reshaped)