# -*- coding: utf-8 -*-
"""task10_mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15j1N4Bw8MUFypE4-3fo1fesxMwFpRROK
"""

import pandas as pd

from google.colab import files
uploaded=files.upload()

df.head()

df=pd.read_csv('retail_store_sales.csv')
df.head()

df.info()

df.describe()

df.isnull().sum()

df['Item']=df.groupby('Category')['Item'].transform(lambda x:x.fillna(x.mode()[0]))

df['Price Per Unit']=df['Price Per Unit'].fillna(df['Price Per Unit'].median())

df['Quantity']=df['Quantity'].fillna(df['Quantity'].fillna(df['Quantity'].median()))

df['Total Spent']=df['Total Spent'].fillna(df['Total Spent'].median())

df['Discount Applied']=df['Discount Applied'].fillna(df['Discount Applied'].mode()[0])

df.info()

df.isnull().sum()

high_sales = df[df['Total Spent'] > 300]

high_sales.head()

df.sort_values('Total Spent', ascending=False).head(10)

category_sales = df.groupby('Category')['Total Spent'].sum()

category_sales

df.head(3)

pivot_table = pd.pivot_table(
    df,
    values='Total Spent',
    index='Payment Method',
    columns='Category',
    aggfunc='sum'
)

pivot_table

"""**Key Insights**
1)Cash generated the highest sales for Butchers, with total sales of 75,350.5.

2)Digital Wallet generated the highest sales for Electric household essentials, with 78,869.0.

3)Credit Card generated the highest sales for Butchers, with 75,545.0 — slightly higher than Cash.

4)Milk Products had the lowest sales across all payment methods, with values ranging from 61,469.5 to 63,209.0.

5)The highest individual value in the entire Pivot Table is 78,869.0, for Electric household essentials using Digital Wallet.
"""

final_dataset=df.to_csv("final_dataset.csv",index=False)

from google.colab import files

files.download("final_dataset.csv")